// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr2tUZ8UgAd6-13Ka0GCp-w2A1V28mByg',
    appId: '1:101820532941:web:f3d6c62ee7991c01ec0184',
    messagingSenderId: '101820532941',
    projectId: 'pekato-ce00c',
    authDomain: 'pekato-ce00c.firebaseapp.com',
    storageBucket: 'pekato-ce00c.appspot.com',
    measurementId: 'G-9M2RC48DKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgO5xrMdHNa5S2MIxmp-v2Fa7I0sSuyRA',
    appId: '1:101820532941:android:2b1661aeeed89636ec0184',
    messagingSenderId: '101820532941',
    projectId: 'pekato-ce00c',
    storageBucket: 'pekato-ce00c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAGRYh6xr5dNrHou9TfP4YZ8LHFVpZJBo',
    appId: '1:101820532941:ios:45df1ace8e1bbcc5ec0184',
    messagingSenderId: '101820532941',
    projectId: 'pekato-ce00c',
    storageBucket: 'pekato-ce00c.appspot.com',
    iosClientId: '101820532941-2jquocankrdg6pelicqp1gl78fo160a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pekato',
  );
}
